### ISSUE TITLE
Add support for Debian 10 

### ISSUE THREAD

**Issue by Scifire** [voxpupuli/puppet-unattended_upgrades#150]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: all
- Ruby: all
- Distribution: Debian 10
- Module version: 4.0.0

## How to reproduce (e.g Puppet code you use)
Include the unattended upgrades class without additional parameters and run` unattended-upgrades --dry-run --debug`

```
class profile::debian {
  include unattended_upgrades
}
```
## What are you seeing
An error occurred, see output log

## What behavior did you expect instead
Working unattended-upgrades ;-)
## Output log
```
An error occurred: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/usr/bin/unattended-upgrades", line 1663, in main
    install_start_time)
  File "/usr/bin/unattended-upgrades", line 1841, in run
    cache, options, allowed_origins, blacklist, whitelist)
  File "/usr/bin/unattended-upgrades", line 1438, in calculate_upgradable_pkgs
    ver_in_allowed_origin(pkg, allowed_origins)
  File "/usr/bin/unattended-upgrades", line 731, in ver_in_allowed_origin
    if is_allowed_origin(ver, allowed_origins):
  File "/usr/bin/unattended-upgrades", line 715, in is_allowed_origin
    if match_whitelist_string(allowed, origin):
  File "/usr/bin/unattended-upgrades", line 565, in match_whitelist_string
    for s in token.split("=")]
ValueError: not enough values to unpack (expected 2, got 1)
Extracting content from /var/log/unattended-upgrades/unattended-upgrades-dpkg.log since 2019-11-13 15:49:26
Traceback (most recent call last):
  File "/usr/bin/unattended-upgrades", line 2195, in <module>
    sys.exit(main(options))
  File "/usr/bin/unattended-upgrades", line 1663, in main
    install_start_time)
  File "/usr/bin/unattended-upgrades", line 1841, in run
    cache, options, allowed_origins, blacklist, whitelist)
  File "/usr/bin/unattended-upgrades", line 1438, in calculate_upgradable_pkgs
    ver_in_allowed_origin(pkg, allowed_origins)
  File "/usr/bin/unattended-upgrades", line 731, in ver_in_allowed_origin
    if is_allowed_origin(ver, allowed_origins):
  File "/usr/bin/unattended-upgrades", line 715, in is_allowed_origin
    if match_whitelist_string(allowed, origin):
  File "/usr/bin/unattended-upgrades", line 565, in match_whitelist_string
    for s in token.split("=")]
ValueError: not enough values to unpack (expected 2, got 1)

```
## Any additional information you'd like to impart
The `50unattended-upgrades` has changed slightly in Debian 10 (Buster) so it now looks like:

```
Unattended-Upgrade::Origins-Pattern {
        "origin=Debian,codename=${distro_codename}-updates";
        "origin=Debian,codename=${distro_codename},label=Debian";
        "origin=Debian,codename=${distro_codename},label=Debian-Security";

```
instead of:
```

Unattended-Upgrade::Origins-Pattern {
        "${distro_id}:${distro_codename}";
        "${distro_id}:${distro_codename}-security";
        "${distro_id}:${distro_codename}-updates";
};
```

**Comment by mfuhrmann** [comment]
@bastelfreak You shouldn't have expose your nickname on the OSMC :-)
Maybe you can help here?

**Comment by bastelfreak** [comment]
Hey, is anybody of you interested in adding a code block for debian 10 at https://github.com/voxpupuli/puppet-unattended_upgrades/blob/master/manifests/params.pp#L50-L73 ?
